version: "3.8"

services:
  profiles-service:
    image: profiles-service
    container_name: profiles-service
    depends_on:
      config-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - edusphere-net
  
  courses-service:
    image: courses-service
    container_name: courses-service
    depends_on:
      config-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - edusphere-net
  
  content-service:
    image: content-service
    container_name: content-service
    depends_on:
      config-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - edusphere-net

  
  postgres:
    image: postgres:16
    container_name: edu-sphere-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: edu
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: edusphere
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U edu"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/config/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - edusphere-net
      
  config-server:
    image: config-server
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 5s
      timeout: 2s
      retries: 10
    networks:
      - edusphere-net

  minio:
    image: minio/minio
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Web UI
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - edusphere-net

volumes:
  pgdata:
  minio-data:

networks:
  edusphere-net:
    driver: bridge
