server:
  port: 8083
  address: 0.0.0.0
  
spring:
  application:
    name: content-service
  
  datasource:
    url: jdbc:postgresql://postgres:5432/content_db
    username: edu
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

content:
  s3:
    endpoint: http://minio:9000
    bucket: content-bucket
    region: us-east-1
    access-key: minio
    secret-key: minio123
